---
extends: default

rules:
  # GitHub Actions uses `on:` which is a truthy key in YAML.
  truthy: false

  # Match repo conventions.
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
